"use client";

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import api from '@/lib/api';

export default function ClaimDetails({ params }: { params: { id: string } }) {
  const router = useRouter();
  const [claim, setClaim] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [uploading, setUploading] = useState(false);

  useEffect(() => {
    api.get(`/api/claims/${params.id}/`)
      .then(res => {
        setClaim(res.data);
        setLoading(false);
      })
      .catch(err => {
        console.error(err);
        setLoading(false);
      });
  }, [params.id]);

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setUploading(true);
    const formData = new FormData();
    formData.append('supporting_document', file);

    try {
      const res = await api.patch(`/api/claims/${claim.id}/`, formData, {
        headers: { 'Content-Type': 'multipart/form-data' }
      });
      setClaim(res.data);
    } catch (err) {
      console.error(err);
      alert('Failed to upload document');
    } finally {
      setUploading(false);
    }
  };

  const handleSubmit = async () => {
    setSubmitting(true);
    try {
      const res = await api.post(`/api/claims/${claim.id}/submit/`);
      setClaim(res.data);
    } catch (err) {
      console.error(err);
      alert('Failed to submit claim');
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) return <div>Loading claim details...</div>;
  if (!claim) return <div>Claim not found</div>;

  const isDraft = claim.status === 'Draft' || claim.status === 'Ready';

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex justify-between items-center bg-white p-6 rounded-lg shadow-sm border border-gray-200">
        <div>
          <h1 className="text-2xl font-bold text-gray-800">Claim {claim.claim_number}</h1>
          <p className="text-gray-500 mt-1">{claim.purchase.product_name} • {claim.benefit.name}</p>
        </div>
        <span className={`px-4 py-2 rounded-full text-sm font-bold ${isDraft ? 'bg-gray-100 text-gray-800' : 'bg-blue-100 text-blue-800'}`}>
          {claim.status}
        </span>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="md:col-span-2 space-y-6">
          <div className="bg-white p-6 rounded-lg shadow-sm border border-blue-200">
            <h2 className="text-lg font-semibold text-blue-900 flex items-center mb-4">
              <span className="mr-2">✨</span> AI Claim Draft
            </h2>
            <div className="bg-blue-50 p-4 rounded-md border border-blue-100 text-blue-800 whitespace-pre-wrap">
              {claim.ai_draft_summary || 'AI summary not available.'}
            </div>
            {isDraft && (
              <p className="text-xs text-gray-500 mt-4">
                This draft was generated by our AI based on your purchase and benefit details.
              </p>
            )}
          </div>

          <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
            <h2 className="text-lg font-semibold text-gray-800 mb-4">Supporting Documents</h2>
            
            {claim.supporting_document ? (
              <div className="flex items-center justify-between p-4 bg-gray-50 rounded border">
                <a href={claim.supporting_document} target="_blank" rel="noreferrer" className="text-blue-600 hover:underline flex items-center">
                  📄 View Attached Document
                </a>
                {isDraft && (
                  <label className="cursor-pointer text-sm text-gray-500 hover:text-gray-700">
                    Replace
                    <input type="file" className="hidden" onChange={handleFileUpload} />
                  </label>
                )}
              </div>
            ) : (
              <div className="text-center p-8 border-2 border-dashed border-gray-300 rounded-lg bg-gray-50">
                {isDraft ? (
                  <label className="cursor-pointer text-blue-600 font-medium hover:text-blue-800">
                    {uploading ? 'Uploading...' : 'Click to upload supporting documents'}
                    <input type="file" className="hidden" onChange={handleFileUpload} disabled={uploading} />
                  </label>
                ) : (
                  <span className="text-gray-500">No documents attached.</span>
                )}
              </div>
            )}
          </div>

          {isDraft && (
            <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200 text-right">
              <button 
                onClick={handleSubmit} 
                disabled={submitting || !claim.supporting_document}
                className="bg-blue-600 text-white px-8 py-3 rounded-md font-bold hover:bg-blue-700 transition disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {submitting ? 'Submitting...' : 'Submit Claim'}
              </button>
              {!claim.supporting_document && (
                <p className="text-red-500 text-sm mt-2">Please upload a supporting document to submit.</p>
              )}
            </div>
          )}
        </div>

        <div className="space-y-6">
          <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
            <h3 className="font-semibold text-gray-800 mb-4">Claim Timeline</h3>
            <ul className="space-y-4">
              <li className="flex gap-4">
                <div className="w-2 h-2 mt-2 rounded-full bg-blue-600"></div>
                <div>
                  <p className="font-medium text-sm">Draft Created</p>
                  <p className="text-xs text-gray-500">{new Date(claim.created_at).toLocaleDateString()}</p>
                </div>
              </li>
              {claim.submitted_at && (
                <li className="flex gap-4">
                  <div className="w-2 h-2 mt-2 rounded-full bg-blue-600"></div>
                  <div>
                    <p className="font-medium text-sm">Submitted</p>
                    <p className="text-xs text-gray-500">{new Date(claim.submitted_at).toLocaleDateString()}</p>
                  </div>
                </li>
              )}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
