# Generated by Django 6.0.7 on 2026-07-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_benefit_purchase_purchasebenefit"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasebenefit",
            name="ai_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
